### ISSUE TITLE
Support for Razer Official SDK C++

### ISSUE THREAD

**Issue by fma965** [Archomeda/lightfx-extender#12]
Hey i know this isn't really a issue but i just thought i check to see if your aware that there is a un-official api for Corsair keyboards.

https://github.com/Palmr/LibCorsairRGB

Also Razer has one too which is actually released
http://developer.razerzone.com/chroma/download/

feel free to close this issue if you already knew.

**Comment by Archomeda** [comment]
I knew about Razer. That one literally went in open beta last week. I didn't know about an unofficial Corsair one. It seems interesting.

> Corsair said they would release a LUA library ...

Makes me sad though :disappointed: why Lua?

**Comment by fma965** [comment]
Yup regarding corsair i think from what i can tell its more for making scripts rather than interacting with applications :/

But this un-official one seems like a good start and you never know... corsair could use it as the official c++ SDK/API or hire the guy lol

**Comment by Archomeda** [comment]
Support for Corsair devices has recently been added by @antonpup in #20. Luckily Corsair has a C++ library called CUESDK. I haven't tested it myself, since I can't, but I hope it works correctly. Currently, I'm in the process of streamlining the support for multiple devices and improving certain parts of the code.

Now that Corsair is supported, I'll change the title to reflect this change.

**Comment by fma965** [comment]
Hi, I'll give it a shot over the weekend and let you know :)

**Comment by Archomeda** [comment]
Also, support for Razer has been added in #21. Again, I can't test it, but since that has been added as well, I'll close this issue.

If there's an issue with these devices, feel free to comment though :)
