### ISSUE TITLE
Doesn't work in Dying Light

### ISSUE THREAD

**Issue by fma965** [Archomeda/lightfx-extender#2]
Hi, It just doesn't work i put the lightfx.dll file in the game and it doesn't show a notification icon or do anything, it does break my actual AlienFX if i use it on a actual alienware system though, i was looking in to coding a thingy to detect alienFX changes and send them to the Logitech LED SDK API's but then i came accross this so decided to give it a try.

I have a alienware 15 (2015) and also a Logitech G600 MMO Mouse, But both dying light and the alienware sample applications didn't work for both the mouse and the actual alienware system when using your DLL. also i can't build your code it gives me a internal error.

**Comment by Archomeda** [comment]
First of all, thanks for trying this! I had expected that it doesn't work out of the box as these versions are still alpha/beta.

When you place this lightfx.dll inside the game folder, this file gets loaded instead of Alienware's, so that's normal (I was actually thinking if it was possible to forward the calls to the original lightfx.dll if present, but I haven't worked it out yet). But what I don't understand, is why it doesn't load. It should place an icon when the game calls `LFX_Initialize`, so I can only guess what's happening here. Granted, the only game I've tried so far is Guild Wars 2.

Anyway, a couple of questions to make me understand the problem better:
- Is it just one game (Dying Light) or are more games affected on your system?
- Can you go to `%APPDATA%` (e.g. `C:\Users\[your_name]\AppData\Roaming`) and see if there's a folder called `LightFX Extender`? If so, see if there the following two files exist: `settings.json` and `LightFXExtender.log`. I would like to see the contents of the log file if it's available.

Regarding building it yourself and the internal error. I have no clue what the problem can be. It works on my system, and also on the [AppVeyor build servers](https://ci.appveyor.com/project/Archomeda/lightfx-extender/history), of which the latter one is a clean system every time it builds. This makes me think the problem is on your end. Are you using Visual Studio 2013? I make use of certain C++11 features that are only available in this version (although I think 2012 should work too).

Edit: Before I forget, what's your Windows version?

**Comment by fma965** [comment]
Hey, thanks for replying, Yes i know it is a alpha/beta, great progress so far.

Yes i know it get's loaded instead of the AlienFX what i meant by saying that was that it does break my existing AlienFX so therefore it's defintely loading the DLL from the correct place.

When i go to the appdata folder it doesn't have any "LIghtFX Extender" i already checked this yesterday when i was looking for the settings.json and log files.

The building issue is probably something to do with my system don't worry bout that for now as all i did was try to build it, haven't looked in to why it didn't build yet.

I am running windows 8.1 9600 you can add me on skype "Fma965_" or Steam "Fma965" if you want. 

Hope this helps and i am happy to test new builds if you need me to. If you can get the forwarding calls working that would be even more amazing :), I'm not going to lie i would love this to work but i doubt my method would be as efficient as yours and a replacement DLL file is defintely a better idea, i deal with vb.net and c# so not really at my level.

Hope this helps.

**Comment by Archomeda** [comment]
Okay, I've investigated the possibilities on why it won't load in Dying Light. And I think I've found the problem. Dying Light is a 64-bit game instead of 32-bit like most games. My lightfx.dll is only built for 32-bit. And it's impossible to directly load a 32-bit library in a 64-bit program.

I would have to make a new configuration for building a 64-bit version before I can get it working on Dying Light.

**Comment by fma965** [comment]
Ok but are you sure this is the problem? I couldn't get it to work with the AlienFX sample SDK applications either, surely they are 32bit?

**Comment by Archomeda** [comment]
I'm pretty sure it is. I've already tried a local x64 build and it seems to be working in Dying Light. If you give me some minutes, I'll make a pull request so you can test it out.

Regarding the samples Alienware provides, I'm not sure how they work exactly, but my guess is that they might do more stuff instead of only calling LightFX.dll.

**Comment by Archomeda** [comment]
Okay, you can see if the build from #3 works for you. Just go to the AppVeyor page, and after you choose x64 there should be a tab called _artifacts_ where you can find the zip.

**Comment by fma965** [comment]
Hi, I;m not seeing any "Artifacts" tab

EDIT: i found it on a older release.

**Comment by fma965** [comment]
Very nice work, it works great, How easy do you think it would be to make a proxy dll? I would be willing to buy you a beer/coffee (via paypal if you got that working :) ) 

Maybe this will help?? https://msdn.microsoft.com/en-us/library/windows/desktop/ms688707%28v=vs.85%29.aspx

http://www.shysecurity.com/posts/Dll%20Proxy

**Comment by Archomeda** [comment]
Haha, I will gladly accept it if you want to do that. But I'll add you on Steam for that since my PayPal email is not the same as the one I use in my commits on GitHub.

I haven't really looked at creating a proxy dll yet. The article you linked doesn't make any sense to me at all :sweat_smile:
Anyway, I've googled a bit, and the process to proxy a dll is not as hard as it seemed. It's just Microsoft being overly complicated. I just need to load the original LightFX.dll and forward the calls. It would involve some coding of course, but it isn't impossible.

And yeah, sorry for the confusion. I added 2 commits after I made the PR. And those were still building in AppVeyor. Luckily there are those little icons next to the commits :smile:

**Comment by fma965** [comment]
Hehe no worries, might be a couple of weeks though sorry as i am skint after buying this alienware laptop :D 

I tried to look in to it but it means nothing to me as i don't do low level stuff like this i just do c# and vb.net and php and stuff...  Hopefully you can get it working, the easiest way i read was to put the original dll in a sub folder and the wrapper one in the main folder but i dunno tbh.

If you get this working then i would really want the g910 keyboard :D so i can have everything in sync :D 

I'm trying to think of a way to detect when i change something in alienFX so i can send it to my mouse (and keyboard if i get it) but the only way i can think would work is to use a timer and constantly monitor the alienware colours (i tried using your dll with commandcenter but i don't think it uses the standard API) 

Anyway great work and feel free to add me on steam, this is a cool project and i hope you won't give up on it :)

EDIT: i just checked your github profile you know a fair amount of different programming languages... or do you just learn the bits you need?
